JAVAC_OPT=-parameters -Xlint:unchecked

PRECEDENT = ../REPOSITORY.swing/REPOSITORY

COPIES = \
	ComprendreSwing.java	\
	ComprendreSwingBorderLayout.java	\
	ComprendreSwingBorderLayoutLarge.java	\
	ComprendreSwingGridLayout.java	\
	ComprendreSwingComplet.java	\
	ComprendreSwingEffacer.java	\
	ComprendreSwingTimer.java	\

DEDUITS = \

FILTRE_CMD = \
	xcfiltre

all:: generes

include ${HOME}/usr/make/java.make
include ${HOME}/usr/make/generes.make
